@isTest
public class testUtilClass{
    /**
    static testMethod void testisSet(){
        Case c = new Case(subject='test', description='test', origin='email');
        insert c;
        
        EmailMessage em = new EmailMessage(subject='test', textbody='test', toAddress='someone@dummaddress1.com', FromAddress='someone@DummyAddress2.com', parentId = c.Id);
        insert em;
                
        system.assert(UtilClass.isSet);
    }
    */

}